//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefono
    {
        public string telefono1 { get; set; }
        public string cedula { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
